atoms/inputの作成
IwaseMio/MioIwase-frontend-basic-2022-todoapp pull request #5
Opened 2023-11-12 06:01 UTC by IwaseMio

2023-11-12 06:06 UTC, JuN-front commented on src/components/Atoms/Input/index.jsx
> +  font-weight: 500;
font-weightに関してはなくても基本問題ないかなとは思います。全体的には動作もできていてgoodです

2023-11-13 05:47 UTC, higashiji2000 requested changes
<img width="546" alt="image" src="https://github.com/IwaseMio/MioIwase-frontend-basic-2022-todoapp/assets/83479175/07ddfa38-8544-408c-8502-a61ea4cfaf2b">
現状このようなエラーがconsoleに表示されています。
コードの問題点は以下で指摘させていただきます！

---
### 修正案

```jsx
export const Input = ({ onEditComplete, defaultValue }) => {
  const inputRef = useRef(null);

  useEffect(() => {
    inputRef.current.value = defaultValue;
    inputRef.current.focus();

    inputRef.current.onblur = (e) => {
      const inputText = e.target.value;
      onEditComplete(inputText);
    };

    inputRef.current.onkeypress = (e) => {
      if (e.key === "Enter") {
        inputRef.current.blur();
      }
    };
  }, []);

  return <StyledInput ref={inputRef} type="text" />;
};
```
リファクタリングも含め、このように修正するのがおすすめです。

2023-11-13 05:47 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  return <StyledInput ref={inputRef} name="input" type="text" />;
```suggestion
  return <StyledInput ref={inputRef} type="text" />;
```
`name` 属性はHTMLフォームにおいてサーバーに送信される情報のキーとして使われる値ですが、今回は入力された値のハンドリングはクライアント側だけで完結します。
そのため、`name` 属性はなくても大丈夫です。

2023-11-13 05:47 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +      });
```suggestion
      inputRef.current.blur();
```

課題に記載された設計とは少し違うかもしれませんが、これでOKです。
input 要素の blur イベントを発火させることで、 useEffect 内で onBlur に登録した関数が実行されます。

2023-11-13 05:47 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +      inputRef.current.onblur();
`onblur` は [blurイベント](https://developer.mozilla.org/ja/docs/Web/API/Element/blur_event) が発生したときに実行する関数を登録するためのプロパティで、 `()` をつけてそのまま実行することは想定されていません。

<img width="537" alt="image" src="https://github.com/IwaseMio/MioIwase-frontend-basic-2022-todoapp/assets/83479175/3b8a6b08-3273-4ebd-96cf-3b3662ab536f">  

実行すると、こんな感じでエラーが発生します。引数に渡されるはずの event が空なためです。

2023-11-13 05:47 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +      });
```suggestion
      inputRef.current.onkeypress(() => {
        onEditComplete(inputRef.current.value);
        onkeypress(inputRef.current.value);
      });
```
`on〇〇` というプロパティの第一引数には、イベントが発火したときに実行される関数を登録します。

```suggestion
      inputRef.current.addEventListener("blur", () => {
        onEditComplete(inputRef.current.value);
        onkeypress(inputRef.current.value);
      });
```
第一引数に `"blur"` を設定するのは、 addEventListener のほうの書き方です。
両者とも同じようにイベントハンドラを設定できるのですが、書き方が大きく違うので注意してください。

2023-11-13 05:47 UTC, higashiji2000 commented on src/components/Atoms/Input/index.jsx
> +  useEffect((props) => {
```suggestion
  useEffect(() => {
```
useEffect に渡す関数は引数を取りません。
ドキュメント：https://ja.react.dev/reference/react/useEffect

2023-11-15 04:27 UTC, higashiji2000 approved these changes
LGTM🏋🏾‍♀️

2023-11-15 23:50 UTC, merged